henhouseproject/fosters/urls.py
from django.urls import path
from .views import FosterListView, FosterCreateView, FosterDetailView, FosterUpdateView, FosterDelete
app_name = 'fosters'

urlpatterns = [

path('', FosterListView.as_view(), name ='foster-list'),
path('create/', FosterCreateView.as_view(), name ='foster-create'),
path('<int:pk>',FosterDetailView.as_view(),name='foster-detail'),
path('<int:pk>/update/',FosterUpdateView.as_view(),name='foster-update'),
path('<int:pk>/delete/',FosterDelete,name='foster-delete'),
]

henhouseproject/henhouseproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from pets.views import LogoutPage, SignupView
from django.conf.urls.static import static
from .views import loginPage
from django.contrib.auth.views import (PasswordResetView, 
                                       PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home, name='main'),
    path('signup/', SignupView.as_view(), name = 'signup'),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', loginPage, name = 'login'),
    path('logout/',LogoutPage,name='logout'),
    path('pets/', include('pets.urls'), name='pets'),
    path('fosters/', include('fosters.urls', namespace='fosters'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

henhouseproject/pets/urls.py
from django.urls import path
from . import views
from .views import ProfileUpdateView

urlpatterns = [
    path('',views.PetList,name='pet-list'),
    
    path('create/',views.PetCreate,name='pet-create'),
    path('<int:pk>',views.PetDetail,name='pet-detail'),
    path('update-pet/<int:pk>',views.PetUpdate,name='pet-update'),
    path('delete-pet/<int:pk>',views.PetDelete,name='pet-delete'),
    path('interested/<int:pk>',views.PetInterested, name='pet-interested'),
    path('application/<int:pk>',views.PetApplication, name='pet-application'),
    path('profile/',views.ProfileView, name='user-profile'),
    path('update-profile/<int:pk>',ProfileUpdateView.as_view(),name='update-profile'),
]

henhouseproject/pets/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth import get_user_model

# Create your models here.


class User(AbstractUser):
    is_foster = models.BooleanField(default=False)
    email = models.EmailField(unique=True)


    def __str__(self):
        return self.email

ANIMAL_CHOICES = (
    ("Dog", "Dog"),
    ("Cat", "Cat")
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=24, blank=True)
    last_name = models.CharField(max_length=24, blank=True)
    occupation = models.CharField(max_length=40, blank=True)
    age = models.IntegerField(default = 0, blank = True)
    phone_number = PhoneNumberField(blank=True)

    def __str__(self):
        return self.user.username


class Pet(models.Model):
    name = models.CharField(max_length=30)
    animal_type = models.CharField(max_length=20, choices=ANIMAL_CHOICES, default='Dog')
    breed_type = models.CharField(max_length=20)
    age = models.IntegerField(null=True)
    city = models.CharField(max_length=30, default='Unknown')
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, default="default.jpg")
    interested = models.ManyToManyField(User, related_name='interested_pets',blank = True)
    applicants = models.ManyToManyField(User, related_name='applicants_pets',blank = True)
    foster = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank = True)

    def __str__(self):
        return self.name



class Foster(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE) 
    
    def __str__(self):
        return self.user.email
    

def post_user_created_signal(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)
post_save.connect(post_user_created_signal, sender=User)


class PetApplication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True) 
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE,blank=True, null=True) 
    message = models.TextField(max_length=200,blank=True, null=True)

    def __str__(self):
        return f'User: {self.user.id}, pet: {self.pet.id}'

henhouseproject/pets/forms.py
from django.forms import ModelForm
from django import forms
from .models import Pet, UserProfile, PetApplication
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


User = get_user_model()

class PetForm(ModelForm):
    class Meta:
        model = Pet
        fields = ['name', 'animal_type', 'breed_type', 'age', 'city', 'description', 'image']
        

class myUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']


class PetApplicationForm(forms.ModelForm):
    class Meta:
        model = PetApplication
        fields = ["message"]

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["first_name", "last_name","occupation", "age", "phone_number"]

henhouseproject/pets/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import Pet, User, UserProfile
from .forms import PetForm, ProfileModelForm, PetApplicationForm
from django.contrib.auth import authenticate,login, logout
from .forms import myUserCreationForm
from django.contrib.auth.decorators import login_required
from django.db.models  import Q
from django.http import HttpResponse
from django.views import generic
from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = myUserCreationForm

    def get_success_url(self):
        return reverse('login')







@login_required(login_url='/login')
def LogoutPage(request):
    logout(request)
    return redirect('main')


@login_required(login_url='/login')
def PetList(request):
    q = request.GET.get('q')
    if q:
        print(q)
        pets = Pet.objects.filter(interested__in =[q])
    else:
        pets = Pet.objects.all()
    context = {'pets':pets}
    return render(request, 'pet-list.html', context )


def PetDetail(request,pk):
    pet = Pet.objects.get(id=pk)
    interested = pet.interested.all()
    application_count = pet.applicants.count()
    interested_count = interested.count()
    context = {'pet':pet, 'interested':interested, 'interested_count':interested_count, 'application_count':application_count}
    return render(request,'pet-detail.html', context)


def check_user_able_to_see_page(function):
    def wrapper(request, *args, **kwargs):
        if request.user.is_foster:
            return function(request, *args, **kwargs)
        return HttpResponse('You are not allowed this action.')

    return wrapper


@login_required(login_url='/login')
@check_user_able_to_see_page
def PetCreate(request):
    page = 'create'
    form = PetForm()
    if request.method == 'POST':
        form = PetForm(request.POST, request.FILES)
        if form.is_valid():
            pet = form.save(commit=False)
            pet.foster = request.user
            pet.save()
            # send_mail(subject="A pet has been created", message="Go to the web site to see the new pet.", from_email="test@test.com", recipient_list=["test2@test.com"])
            return redirect('pet-list')

    context={'form':form, 'page':page}
    return render(request, 'pet-form.html', context)


@login_required(login_url='/login')
def PetUpdate(request,pk):
    page = 'update'
    pet = Pet.objects.get(id=pk)
    form = PetForm(instance=pet)

    if request.user != pet.foster:
        return HttpResponse('You are not allowed this action.')
    
    if request.method == 'POST':
        form = PetForm(request.POST, request.FILES, instance=pet)
        if form.is_valid:
            form.save()
            return redirect('pet-detail', pk=pet.id)
    context = {'form':form, 'page':page, 'pet':pet}
    return render(request, 'pet-form.html', context)    


@login_required(login_url='/login')
def PetDelete(request,pk):
    pet = Pet.objects.get(id=pk)

    if request.user != pet.foster:
        return HttpResponse('You are not allowed this action.')   
     
    if request.method == 'POST':
        pet.delete()
        return redirect('pet-list')
    return render(request, 'delete.html', {'obj':pet})



def PetInterested(request,pk):
    pet = Pet.objects.get(id=pk)
    interested = pet.interested.all()
    if request.method == 'POST':
        if request.user in interested:
            pet.interested.remove(request.user)
        else:
            pet.interested.add(request.user)
    return redirect('pet-detail', pk=pet.id)


@login_required(login_url='/login')
def PetApplication(request,pk):
    user = request.user
    profile = UserProfile.objects.get(user=user)
    pet = Pet.objects.get(id=pk)
    form = PetApplicationForm()
    applicants = pet.applicants.all()

    if request.user in applicants:
        return HttpResponse('You have already applied for this pet')
    if request.method == 'POST':
        form = PetApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.user = user
            application.pet = pet
            application.save()
            pet.applicants.add(user)
            pet.save()
            return redirect('pet-detail', pk=pet.id)
        else:
            form = PetApplicationForm()
    context = {'pet':pet, 'user':user, 'profile':profile, 'form':form}
    return render(request,'pet-application.html',context)



@login_required(login_url='/login')
def ProfileView(request):
    user = request.user
    print(user.id)
    profile = UserProfile.objects.get(user=user)
    context = {'user':user, 'profile':profile}
    return render(request,'user-profile.html',context)


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "update-profile.html"
    form_class = ProfileModelForm

    def get_success_url(self):
        return reverse("user-profile")
    
    def get_queryset(self):
        return UserProfile.objects.all()

henhouseproject/templates/delete.html
{% comment %} {%extends 'main.html'%}
<form class="form" action="" method="POST">
  {%csrf_token%}
  <div class="form__group">
    <p>Are you sure you want to delete "{{obj}}"?</p>
  </div>

  <div class="for__group">
    <input class="btn btn--main" type="submit" value="Confirm" />
  </div>
</form>
{% endcomment %}

<form class="form" action="" method="POST">
  {%csrf_token%}
  <div class="form__group">
    <p>Are you sure you want to delete "{{obj}}"?</p>
  </div>

  <div class="for__group">
    <input class="p-2 bg-blue-500 text-white" type="submit" value="Confirm" />
  </div>
</form>

henhouseproject/templates/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hen's House</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div class="bg-blue-600 text-white  ">
<div class='p-6 flex justify-between items-center'>
      <div class="text-4xl">Hen's House</div>
      <div><a href="{%url 'pet-list'%}">Pet List</a></div>
      {%if request.user.is_authenticated%}
      {%if request.user.is_superuser%}
      <div><a href="{%url 'fosters:foster-list'%}">Foster List</a></div>
      {%endif%}
       <div><a href="{%url 'user-profile' %}">My Profile</a></div>
      <div>
        <div>Welcome, {{request.user.username}}</div>
        <a href="{%url 'logout'%}">Logout</a>
        {%else%}
        <a href="{%url 'login'%}">Login</a>
      </div>
      {%endif%}
      </div>
</div>
    </div>
    <div class="text-2xl p-4">
      We help find homes for pets! We provide a platform for people who are
      fostering animals to find their new family.
    </div>

    <div class='m-auto'>{% block content%} {% endblock %}</div>
  </body>
</html>

henhouseproject/templates/pet-application.html
{%extends 'main.html'%}{% load tailwind_filters %} {% block content %}
<h1>Pet application for {{pet.name}}</h1>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{form|crispy}}
  <button class="p-2 bg-blue-500" type="Submit">Apply</button>
</form>
{% endblock content %}

henhouseproject/templates/pet-detail.html
{%extends 'main.html'%} {%block content%}

<a class="p-4" href="{%url 'pet-list'%}">Back to Pet List</a>

<div class="flex justify-center items-center gap-4">
  <div>
    <img
      class="h-[240px] w-[200px] object-cover rounded-md"
      src="{{pet.image.url}}"
      alt="pet-image"
    />
  </div>
  <div class="gap-2">
    <h1>Name: {{pet.name}}</h1>
    <p>Type: {{pet.animal_type}}, Breed: {{pet.breed_type}}</p>
    <p>Age: {{pet.age}}</p>
    <p>City: {{pet.city}}</p>
    <p>Description: {{pet.description}}</p>
    <p>Current Foster: {{pet.foster}}</p>
  </div>
</div>

<form
  class="flex flex-col justify-center items-center p-4 gap-4"
  method="POST"
  action="{%url 'pet-interested' pet.id%}"
>
  {{interested_count}} person interested {% csrf_token %} 
  {%if request.user in interested%}
  <button
    class="p-2 bg-blue-500 text-white"
    type="submit"
    name="pet_id"
    value="{{pet.id}}"
  >
    Remove Interest
  </button>
  {%else%}
  <button
    class="p-2 bg-blue-500 text-white"
    type="submit"
    name="pet_id"
    value="{{pet.id}}"
  >
    Express Interest
  </button>
  {%endif%}
</form>
<div>{{application_count}} Application(s)</div>
<a href="{%url 'pet-application' pet.id%}">Apply here</a>
<hr />
<div class="flex justify-center items-center gap-4 p-4 text-white">
  <button class="p-2 bg-blue-500">
    <a href="{%url 'pet-update' pet.id %}">Update</a>
  </button>
  <button class="p-2 bg-blue-500">
    <a href="{%url 'pet-delete' pet.id %}">Delete</a>
  </button>
</div>
{%endblock%}

henhouseproject/templates/pet-form.html
{%extends 'main.html'%}{% load tailwind_filters %}{%block content%}
<div class="w-[100%] flex flex-col justify-center items-center">
  {%if page == 'create'%}
  <h1>Add a new pet!</h1>
  {%else%}
  <h1>Update an existing pet</h1>
  {%endif%}
  <form
    class="flex flex-col justify-center items-center w-[50%]"
    action=""
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %} {{form|crispy}} {%if page == 'create'%}
    <button class="p-2 text-white bg-blue-500" type="submit">Add pet</button>
    <a href="{%url 'pet-list' %}">Cancel</a>
    {%else%}
    <button class="p-2 text-white bg-blue-500" type="submit">Update pet</button>
    <a href="{%url 'pet-detail' pet.id%}">Cancel</a>
    {%endif%}
  </form>
  {% comment %}
  <form class="form" method="POST" action="" enctype="multipart/form-data">
    {% csrf_token%} {%for field in form%}
    <div>
      <label for="">{{field.label}}</label>
      {{field}}
    </div>
    {%endfor block%} {%if page == 'create'%}
    <button type="submit">Add pet</button>
    <a href="{%url 'pet-list' %}">Cancel</a>
    {%else%}
    <button type="submit">Update pet</button>
    <a href="{%url 'pet-detail' pet.id%}">Cancel</a>
    {%endif%}
  </form>
  {% endcomment %} {%endblock%}
</div>

henhouseproject/templates/pet-list.html
{%extends 'main.html'%} {% load static %} {% block content %}

<main
  class="w-[80vw] m-auto bg-slate-100 flex flex-col justify-center items-center p-6"
>
  <h1 class="text-3xl">Our Pets</h1>

  <form class="p-6" method="GET" action="{%url 'pet-list' %}">
    <div class="flex gap-6">
      <button class="p-2 bg-blue-500 text-white" name="q" value="">
        All Pets
      </button>
      <button
        class="p-2 bg-blue-500 text-white"
        name="q"
        value="{{request.user.id}}"
      >
        My Interested List
      </button>
    </div>
  </form>
  <section class="flex justify-center items-center flex-wrap gap-8 py-2 mb-4">
    {%for pet in pets%}
    <div class="">
      <a href="{%url 'pet-detail' pet.id %}">
        <img
          class="h-[240px] w-[200px] object-cover object-center m-2 rounded-md"
          src="{{pet.image.url}}"
        />
        <p class="text-xl text-center">{{pet.name}}</p>
      </a>
    </div>

    {%endfor block%}
  </section>

  {%if user.is_authenticated%}
  <button class="p-2 bg-blue-500 text-white">
    <a href="{%url 'pet-create'%}">Add a pet</a>
  </button>
  {%endif%} {%endblock%}
</main>

henhouseproject/templates/update-profile.html
{%extends 'main.html'%} {% block content %}

<h1>Update Profile</h1>

<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <div class="p-4 gap-4 flex">
    <button class="p-2 bg-blue-500 text-white" type="submit">
      Confirm Update
    </button>
    <button class="p-2 bg-blue-500 text-white" type="submit">
      <a href="{%url 'user-profile'%}">Cancel</a>
    </button>
  </div>
</form>
{%endblock content%}

henhouseproject/templates/user-profile.html
{%extends 'main.html'%} {% block content %}
<div class="p-6 flex flex-col gap-3">
  {%if request.user.is_foster%}
  <h1 class="text-2xl">Foster profile</h1>
  {%else%}
  <h1 class="text-2xl">User profile</h1>
  {%endif%}
  <div>Username: {{user.username}}</div>
  <div>First Name: {{profile.first_name}}</div>
  <div>Last Name: {{profile.last_name}}</div>
  <div>Age: {{profile.age}}</div>
  <div>Occupation: {{profile.occupation}}</div>
  <hr />
  <div>
    Contact
    <div>E-mail: {{user.email}}</div>
    <div>Phone: {{profile.phone_number}}</div>
  </div>
  <a href="{%url 'update-profile' user.id%}"
    ><button class="p-2 bg-blue-500 text-white">Update</button></a
  >
</div>
<a href="{%url 'password-reset'%}">Reset Password</a>
{% endblock content %}