henhouseproject/fosters/urls.py
from django.urls import path
from .views import FosterListView, FosterCreateView, FosterDetailView, FosterUpdateView, FosterDelete
app_name = 'fosters'

urlpatterns = [

path('', FosterListView.as_view(), name ='foster-list'),
path('create/', FosterCreateView.as_view(), name ='foster-create'),
path('<int:pk>',FosterDetailView.as_view(),name='foster-detail'),
path('<int:pk>/update/',FosterUpdateView.as_view(),name='foster-update'),
path('<int:pk>/delete/',FosterDelete,name='foster-delete'),
]

henhouseproject/henhouseproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from pets.views import LogoutPage, SignupView
from django.conf.urls.static import static
from .views import loginPage
from django.contrib.auth.views import (PasswordResetView, 
                                       PasswordResetDoneView,PasswordResetConfirmView, PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home, name='main'),
    path('signup/', SignupView.as_view(), name = 'signup'),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', loginPage, name = 'login'),
    path('logout/',LogoutPage,name='logout'),
    path('pets/', include('pets.urls'), name='pets'),
    path('fosters/', include('fosters.urls', namespace='fosters'))

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

henhouseproject/pets/urls.py
from django.urls import path
from . import views
from .views import ProfileUpdateView

urlpatterns = [
    path('',views.PetList,name='pet-list'),
    
    path('create/',views.PetCreate,name='pet-create'),
    path('<int:pk>',views.PetDetail,name='pet-detail'),
    path('update-pet/<int:pk>',views.PetUpdate,name='pet-update'),
    path('delete-pet/<int:pk>',views.PetDelete,name='pet-delete'),
    path('interested/<int:pk>',views.PetInterested, name='pet-interested'),
    path('application/<int:pk>',views.PetApplication, name='pet-application'),
    path('profile/',views.ProfileView, name='user-profile'),
    path('update-profile/<int:pk>',ProfileUpdateView.as_view(),name='update-profile'),
]

henhouseproject/fosters/models.py
from django.db import models

# Create your models here.

henhouseproject/fosters/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class FosterModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name', 
            'last_name', 
            'email'
        )

henhouseproject/fosters/views.py
import random
from django.shortcuts import render, reverse, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from pets.models import Foster, User
from .forms import FosterModelForm
from django.core.mail import send_mail
from .mixins import FosterAndLoginRequiredMixin, SuperUserRequiredMixin

# Create your views here.


class FosterListView(LoginRequiredMixin, generic.ListView):
    template_name = "fosters/foster_list.html"

    def get_queryset(self):
        return Foster.objects.all()
    


class FosterCreateView(SuperUserRequiredMixin, generic.CreateView):
    template_name = "fosters/foster_create.html"
    form_class = FosterModelForm

    def get_success_url(self):
        return reverse("fosters:foster-list")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_foster = True
        user.username = f'{user.first_name}{user.last_name}'
        random_password = random.randint(0,100000)
        user.set_password(f"{random_password}")
        user.save()
        Foster.objects.create(
            user=user,
            user_profile=user.userprofile,
        )
        send_mail(
            subject="You are invited to be an approved Foster for Hen's House",
            message=f"Congratulations. You are approved as a Foster for Hen's House. Please come login at https://henhouseproject.vercel.app/ to get started. Your temporary password is {random_password}. You can reset your password if you want to in your user profile page by clicking reset password."
            ,
            from_email="admin@henshouse.com", 
            recipient_list=[user.email]
        )
        # foster.user_profile = self.request.user.userprofile
        # foster.save()
        return super(FosterCreateView, self).form_valid(form)
    

class FosterDetailView(LoginRequiredMixin, generic.DetailView):
    template_name= "fosters/foster_detail.html"
    context_object_name = "foster"

    def get_queryset(self):
        return Foster.objects.all()



class FosterUpdateView(FosterAndLoginRequiredMixin, generic.UpdateView):
    template_name = "fosters/foster_update.html"
    form_class = FosterModelForm

    def get_success_url(self):
        return reverse("fosters:foster-list")
    
    def get_queryset(self):
        return Foster.objects.all()
    

# class FosterDeleteView(SuperUserRequiredMixin, generic.DeleteView):
#     template_name= "fosters/foster_delete.html"
#     context_object_name = "user"

#     def get_queryset(self):
#         return User.objects.all()
    
#     def get_success_url(self):
#         return reverse("fosters:foster-list")
    


def FosterDelete(request,pk):
    foster = Foster.objects.get(id=pk)
    user = foster.user
     
    if request.method == 'POST':
        user.delete()
        return redirect('fosters:foster-list')
    return render(request, 'fosters/foster_delete.html', {'obj':user})

henhouseproject/fosters/templates/fosters/foster_create.html
{%extends 'main.html'%}{% load tailwind_filters %} {% block content %}

<a href="{%url 'fosters:foster-list'%}">Back to Foster List</a>
<h1>Create Foster</h1>

<form action="" method="post">
  {% csrf_token %} {{form|crispy}}
  <button class="p-2 bg-blue-500 text-white" type="submit">Submit</button>
</form>

{%endblock content%}

henhouseproject/fosters/templates/fosters/foster_delete.html
{%extends 'main.html'%} {% block content %}

<a href="{%url 'fosters:foster-list'%}">Back to Foster List</a>
<h1>Delete Foster</h1>
<hr />
<h1>Are you sure you want to delete this Foster?</h1>
<div>{{foster.user.username}}</div>
<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <button class="p-2 bg-blue-500 text-white" type="submit">Delete</button>
</form>

{%endblock content%}

henhouseproject/fosters/templates/fosters/foster_detail.html
{%extends 'main.html'%} {%block content%} {{foster.user.username}}

<div class="flex gap-6">
  <button class="p-2 bg-blue-500 text-white">
    <a href="{%url 'fosters:foster-update' foster.id%}">Update</a>
  </button>
  <button class="p-2 bg-blue-500 text-white">
    <a href="{%url 'fosters:foster-delete' foster.id%}">Delete</a>
  </button>
</div>

{%endblock content%}

henhouseproject/fosters/templates/fosters/foster_list.html
{%extends 'main.html'%} {% block content %}
<div class="flex flex-col w-[80%] justify-center items-center mt-10 space-y-5">
  <h1>Our Approved Fosters</h1>
  <div>
    {%for foster in object_list%}
    <div>
      <a href="{%url 'fosters:foster-detail' foster.id%}"
        >{{foster.user.username}}</a
      >: {{foster.user.email}}
    </div>
    {%endfor%}
  </div>

  <button class="p-2 bg-blue-500 text-white">
    <a href="{%url 'fosters:foster-create'%}">Add a foster</a>
  </button>
</div>
{%endblock content%}

henhouseproject/fosters/templates/fosters/foster_update.html
{%extends 'main.html'%} {% block content %}

<a href="{%url 'fosters:foster-list'%}">Back to Foster List</a>
<h1>Update Foster</h1>

<form action="" method="post">
  {% csrf_token %} {{form.as_p}}
  <button class="p-2 bg-blue-500 text-white" type="submit">Update</button>
</form>

{%endblock content%}